apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 940090592876.dkr.ecr.us-east-1.amazonaws.com/result:1.0.1
        name: result
        ports:
        - containerPort: 80
          name: result
